INSERT INTO delivery.TB_PACKAGE
(ID, NAME)
VALUES
(99, 'Package_Name');

INSERT INTO public.TB_PRODUCT
(ID, NAME, QUANTITY_STOCK, DESCRIPTION, DELIVERY_STATUS, PACKAGE_ID)
VALUES
(99, 'Product_Name', 15, 'Description', 'DISPATCHED', 99);

INSERT INTO public.TB_LABEL
(ID, NAME)
VALUES
(99, 'Label_Name');

INSERT INTO public.TB_PRODUCTS_LABELS
(PRODUCT_ID, LABEL_ID)
VALUES
(99, 99);
