INSERT INTO delivery.TB_PACKAGE
(ID, NAME)
VALUES
(1, 'Package_Name');

INSERT INTO public.TB_PRODUCT
(ID, NAME, QUANTITY_STOCK, DESCRIPTION, DELIVERY_STATUS, PACKAGE_ID)
VALUES
(1, 'Product_Name', 10, 'Description', 'DISPATCHED', 1);

INSERT INTO public.TB_LABEL
(ID, NAME)
VALUES
(1, 'Label_Name');

INSERT INTO public.TB_PRODUCTS_LABELS
(PRODUCT_ID, LABEL_ID)
VALUES
(1, 1);
