server:
  port: 8080
  host: localhost
  servlet:
    context-path: /lunar_ecommerce/clothing

h2:
  scope: test

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/my_pgdb
#    username: postgres
#    password: 123456
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none # <create | create-drop | update | validate | none>
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true

database:
  username: ${DATABASE_USERNAME:src/main/resources/database/secret-db-username}
  password: ${DATABASE_PASSWORD:src/main/resources/database/secret-db-password}
  driverClassName: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/my_pgdb}
  poolName: ${POOL_NAME:MyAppPool}
  minPoolSize: ${MIN_POOL_SIZE:1}
  maxPoolSize: ${MAX_POOL_SIZE:10}
  maxLifetime: ${MAX_LIFETIME:1800000}
  validationTimeout: ${VALIDATION_TIMEOUT:250}
  connectionTimeout: ${CONNECTION_TIMEOUT:30000}
  idleTimeout: ${IDLE_TIMEOUT:30000}